<?php
/**
 * FaceMatchResponseSchema
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Cashfree
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cashfree Verification API's.
 *
 * Cashfree's Verification APIs provide different types of verification to our merchants.
 *
 * The version of the OpenAPI document: 2023-12-18
 * Contact: developers@cashfree.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Cashfree\Model;

use \ArrayAccess;
use \Cashfree\ObjectSerializer;

/**
 * FaceMatchResponseSchema Class Doc Comment
 *
 * @category Class
 * @description Success response for Face Match API
 * @package  Cashfree
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FaceMatchResponseSchema implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'FaceMatchResponseSchema';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'status' => 'string',
        'ref_id' => 'int',
        'verification_id' => 'string',
        'face_match_result' => 'string',
        'face_match_score' => 'float',
        'mask_detected_first_image' => 'bool',
        'mask_detected_score_first_image' => 'string',
        'mask_detected_second_image' => 'bool',
        'mask_detected_score_second_image' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'status' => null,
        'ref_id' => null,
        'verification_id' => null,
        'face_match_result' => null,
        'face_match_score' => null,
        'mask_detected_first_image' => null,
        'mask_detected_score_first_image' => null,
        'mask_detected_second_image' => null,
        'mask_detected_score_second_image' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static $openAPINullables = [
        'status' => false,
		'ref_id' => false,
		'verification_id' => false,
		'face_match_result' => false,
		'face_match_score' => false,
		'mask_detected_first_image' => false,
		'mask_detected_score_first_image' => false,
		'mask_detected_second_image' => false,
		'mask_detected_score_second_image' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'status' => 'status',
        'ref_id' => 'ref_id',
        'verification_id' => 'verification_id',
        'face_match_result' => 'face_match_result',
        'face_match_score' => 'face_match_score',
        'mask_detected_first_image' => 'maskDetected_first_image',
        'mask_detected_score_first_image' => 'maskDetected_score_first_image',
        'mask_detected_second_image' => 'maskDetected_second_image',
        'mask_detected_score_second_image' => 'maskDetected_score_second_image'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'status' => 'setStatus',
        'ref_id' => 'setRefId',
        'verification_id' => 'setVerificationId',
        'face_match_result' => 'setFaceMatchResult',
        'face_match_score' => 'setFaceMatchScore',
        'mask_detected_first_image' => 'setMaskDetectedFirstImage',
        'mask_detected_score_first_image' => 'setMaskDetectedScoreFirstImage',
        'mask_detected_second_image' => 'setMaskDetectedSecondImage',
        'mask_detected_score_second_image' => 'setMaskDetectedScoreSecondImage'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'status' => 'getStatus',
        'ref_id' => 'getRefId',
        'verification_id' => 'getVerificationId',
        'face_match_result' => 'getFaceMatchResult',
        'face_match_score' => 'getFaceMatchScore',
        'mask_detected_first_image' => 'getMaskDetectedFirstImage',
        'mask_detected_score_first_image' => 'getMaskDetectedScoreFirstImage',
        'mask_detected_second_image' => 'getMaskDetectedSecondImage',
        'mask_detected_score_second_image' => 'getMaskDetectedScoreSecondImage'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('ref_id', $data ?? [], null);
        $this->setIfExists('verification_id', $data ?? [], null);
        $this->setIfExists('face_match_result', $data ?? [], null);
        $this->setIfExists('face_match_score', $data ?? [], null);
        $this->setIfExists('mask_detected_first_image', $data ?? [], null);
        $this->setIfExists('mask_detected_score_first_image', $data ?? [], null);
        $this->setIfExists('mask_detected_second_image', $data ?? [], null);
        $this->setIfExists('mask_detected_score_second_image', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status It displays the status of the API request.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets ref_id
     *
     * @return int|null
     */
    public function getRefId()
    {
        return $this->container['ref_id'];
    }

    /**
     * Sets ref_id
     *
     * @param int|null $ref_id It displays the unique ID created by Cashfree Payments for reference purposes.
     *
     * @return self
     */
    public function setRefId($ref_id)
    {
        if (is_null($ref_id)) {
            throw new \InvalidArgumentException('non-nullable ref_id cannot be null');
        }
        $this->container['ref_id'] = $ref_id;

        return $this;
    }

    /**
     * Gets verification_id
     *
     * @return string|null
     */
    public function getVerificationId()
    {
        return $this->container['verification_id'];
    }

    /**
     * Sets verification_id
     *
     * @param string|null $verification_id It displays the unique ID you created to identify the API request.
     *
     * @return self
     */
    public function setVerificationId($verification_id)
    {
        if (is_null($verification_id)) {
            throw new \InvalidArgumentException('non-nullable verification_id cannot be null');
        }
        $this->container['verification_id'] = $verification_id;

        return $this;
    }

    /**
     * Gets face_match_result
     *
     * @return string|null
     */
    public function getFaceMatchResult()
    {
        return $this->container['face_match_result'];
    }

    /**
     * Sets face_match_result
     *
     * @param string|null $face_match_result It displays the result of the face match verification request.
     *
     * @return self
     */
    public function setFaceMatchResult($face_match_result)
    {
        if (is_null($face_match_result)) {
            throw new \InvalidArgumentException('non-nullable face_match_result cannot be null');
        }
        $this->container['face_match_result'] = $face_match_result;

        return $this;
    }

    /**
     * Gets face_match_score
     *
     * @return float|null
     */
    public function getFaceMatchScore()
    {
        return $this->container['face_match_score'];
    }

    /**
     * Sets face_match_score
     *
     * @param float|null $face_match_score It displays the score of the face match verification request.
     *
     * @return self
     */
    public function setFaceMatchScore($face_match_score)
    {
        if (is_null($face_match_score)) {
            throw new \InvalidArgumentException('non-nullable face_match_score cannot be null');
        }
        $this->container['face_match_score'] = $face_match_score;

        return $this;
    }

    /**
     * Gets mask_detected_first_image
     *
     * @return bool|null
     */
    public function getMaskDetectedFirstImage()
    {
        return $this->container['mask_detected_first_image'];
    }

    /**
     * Sets mask_detected_first_image
     *
     * @param bool|null $mask_detected_first_image It displays whether the individual in the image 1 is wearing a mask.
     *
     * @return self
     */
    public function setMaskDetectedFirstImage($mask_detected_first_image)
    {
        if (is_null($mask_detected_first_image)) {
            throw new \InvalidArgumentException('non-nullable mask_detected_first_image cannot be null');
        }
        $this->container['mask_detected_first_image'] = $mask_detected_first_image;

        return $this;
    }

    /**
     * Gets mask_detected_score_first_image
     *
     * @return string|null
     */
    public function getMaskDetectedScoreFirstImage()
    {
        return $this->container['mask_detected_score_first_image'];
    }

    /**
     * Sets mask_detected_score_first_image
     *
     * @param string|null $mask_detected_score_first_image It displays the score of the mask detection analysis for image 1.
     *
     * @return self
     */
    public function setMaskDetectedScoreFirstImage($mask_detected_score_first_image)
    {
        if (is_null($mask_detected_score_first_image)) {
            throw new \InvalidArgumentException('non-nullable mask_detected_score_first_image cannot be null');
        }
        $this->container['mask_detected_score_first_image'] = $mask_detected_score_first_image;

        return $this;
    }

    /**
     * Gets mask_detected_second_image
     *
     * @return bool|null
     */
    public function getMaskDetectedSecondImage()
    {
        return $this->container['mask_detected_second_image'];
    }

    /**
     * Sets mask_detected_second_image
     *
     * @param bool|null $mask_detected_second_image It displays whether the individual in the image 1 is wearing a mask.
     *
     * @return self
     */
    public function setMaskDetectedSecondImage($mask_detected_second_image)
    {
        if (is_null($mask_detected_second_image)) {
            throw new \InvalidArgumentException('non-nullable mask_detected_second_image cannot be null');
        }
        $this->container['mask_detected_second_image'] = $mask_detected_second_image;

        return $this;
    }

    /**
     * Gets mask_detected_score_second_image
     *
     * @return string|null
     */
    public function getMaskDetectedScoreSecondImage()
    {
        return $this->container['mask_detected_score_second_image'];
    }

    /**
     * Sets mask_detected_score_second_image
     *
     * @param string|null $mask_detected_score_second_image It displays the score of the mask detection analysis for image 2.
     *
     * @return self
     */
    public function setMaskDetectedScoreSecondImage($mask_detected_score_second_image)
    {
        if (is_null($mask_detected_score_second_image)) {
            throw new \InvalidArgumentException('non-nullable mask_detected_score_second_image cannot be null');
        }
        $this->container['mask_detected_score_second_image'] = $mask_detected_score_second_image;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


