<?php
/**
 * AdvanceEmploymentResponseRecentEmploymentDetailsEmployerDetailsPfFilingDetailsInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Cashfree
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cashfree Verification API's.
 *
 * Cashfree's Verification APIs provide different types of verification to our merchants.
 *
 * The version of the OpenAPI document: 2023-12-18
 * Contact: developers@cashfree.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Cashfree\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AdvanceEmploymentResponseRecentEmploymentDetailsEmployerDetailsPfFilingDetailsInnerTest Class Doc Comment
 *
 * @category    Class
 * @description AdvanceEmploymentResponseRecentEmploymentDetailsEmployerDetailsPfFilingDetailsInner
 * @package     Cashfree
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AdvanceEmploymentResponseRecentEmploymentDetailsEmployerDetailsPfFilingDetailsInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AdvanceEmploymentResponseRecentEmploymentDetailsEmployerDetailsPfFilingDetailsInner"
     */
    public function testAdvanceEmploymentResponseRecentEmploymentDetailsEmployerDetailsPfFilingDetailsInner()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_amount"
     */
    public function testPropertyTotalAmount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "employees_count"
     */
    public function testPropertyEmployeesCount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "wage_month"
     */
    public function testPropertyWageMonth()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
