<?php
/**
 * AdvanceEmploymentResponseRecentEmploymentDetailsEmployeeDetailsEpfoTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Cashfree
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cashfree Verification API's.
 *
 * Cashfree's Verification APIs provide different types of verification to our merchants.
 *
 * The version of the OpenAPI document: 2023-12-18
 * Contact: developers@cashfree.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Cashfree\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AdvanceEmploymentResponseRecentEmploymentDetailsEmployeeDetailsEpfoTest Class Doc Comment
 *
 * @category    Class
 * @description It contains the information found in Employees&#39; Provident Fund Organisation (EPFO)
 * @package     Cashfree
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AdvanceEmploymentResponseRecentEmploymentDetailsEmployeeDetailsEpfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AdvanceEmploymentResponseRecentEmploymentDetailsEmployeeDetailsEpfo"
     */
    public function testAdvanceEmploymentResponseRecentEmploymentDetailsEmployeeDetailsEpfo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "recent"
     */
    public function testPropertyRecent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name_unique"
     */
    public function testPropertyNameUnique()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pf_filings_details"
     */
    public function testPropertyPfFilingsDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
